# Nessus Configuration File
web_server_port = 8834
web_server_listen_address = 0.0.0.0
plugin_feed_disabled = 0
syslog_enabled = 1
syslog_port = 514
scanner_listen_address = 0.0.0.0
scanner_listen_port = 8834
